#!/bin/sh

DAEMON=/opt/bin/python2.7
PARAMETERS="/opt/web-apps/web2py/web2py.py -K cpfecys"
LOGFILE=/var/log/web2py-scheduler.log

start() {
    echo -n "starting up $DAEMON $PARAMETERS"
    nohup $DAEMON $PARAMETERS > $LOGFILE 2>&1 &
    if [ "$?" -eq 0 ]; then
        echo " Done."
    else
        echo " FAILED."
    fi
}
stop() {
    echo "This Process takes 1 minute to finish..."
    kill `ps -ef | grep "web2py.py -K cpfecys" | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
}
status() {
    kill -0 `ps -ef | grep "web2py.py -K cpfecys" | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
    if [ "$?" -eq 0 ]; then
        echo "Running."
    else
        echo "Not Running."
    fi
}
case "$1" in
    start)
    start
    ;;
    restart)
    stop
    sleep 60
    start
    ;;
    stop)
    stop
    ;;
    status)
    status
    ;;
    *)
    echo "usage : $0 start|restart|stop|status"
    ;;
esac
exit 0
# chkconfig: 2345 90 10
# description: web2py-scheduler-cpecys
