#!/bin/sh

DAEMON=/opt/bin/python2.7
PARAMETERS="/opt/web-apps/web2py/web2py.py -K cpfecys"
LOGFILE=/var/log/web2py-scheduler.log

start() {
    echo -n "starting up $DAEMON"
    RUN=`$DAEMON $PARAMETERS > $LOGFILE 2>&1`
    if [ "$?" -eq 0 ]; then
        echo " Done."
    else
        echo " FAILED."
    fi
}
stop() {
    killall $DAEMON
}
status() {
    killall -0 $DAEMON
    if [ "$?" -eq 0 ]; then
        echo "Running."
    else
        echo "Not Running."
    fi
}
case "$1" in
    start)
    start
    ;;
    restart)
    stop
    sleep 2
    start
    ;;
    stop)
    stop
    ;;
    status)
    status
    ;;
    *)
    echo "usage : $0 start|restart|stop|status"
    ;;
esac
exit 0
# chkconfig: 2345 90 10
# description: web2py-scheduler
